apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.config.JWT_SECRET | quote }}
  ADMIN_EMAIL: {{ .Values.config.ADMIN_EMAIL | quote }}
  ADMIN_PASSWORD: {{ .Values.config.ADMIN_PASSWORD | quote }}
  POSTGRES_USER: {{ .Values.database.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.env.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.database.env.POSTGRES_DB | quote }}
