apiVersion: v1
kind: Secret
metadata:
  name: db-app-secret
  namespace: citizen-portal
type: Opaque
stringData:
  username: "db_user"
  password: "<POSTGRES_PASSWORD_PLACEHOLDER>"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: citizen-portal
  labels:
    app: db
spec:
  inheritedMetadata:
    labels:
      app: db
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.8
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: citizen_portal
      owner: db_user
      secret:
        name: db-app-secret
  storage:
    size: 5Gi
