apiVersion: batch/v1
kind: Job
metadata:
  name: pg-restore
  namespace: citizen-portal
spec:
  template:
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: pg-restore
        image: postgres:15
        # Provide the filename as the argument below. Example: db_backup_2026-06-21_02-00-00.sql.enc
        command: ["/bin/bash", "/scripts/restore.sh", "<BACKUP_FILENAME_HERE>"]
        envFrom:
          - secretRef:
              name: citizen-portal-secret
        volumeMounts:
          - name: backup-storage
            mountPath: /backups
          - name: backup-scripts
            mountPath: /scripts
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: pg-backup-pvc
        - name: backup-scripts
          configMap:
            name: pg-backup-scripts
            defaultMode: 0755
      restartPolicy: Never
