apiVersion: v1
kind: Secret
metadata:
  name: citizen-portal-secret
  namespace: citizen-portal
type: Opaque
stringData:
  DATABASE_URL: "postgres://db_user:<POSTGRES_PASSWORD_PLACEHOLDER>@db-rw:5432/citizen_portal"
  POSTGRES_USER: "db_user"
  POSTGRES_PASSWORD: "<POSTGRES_PASSWORD_PLACEHOLDER>"
  POSTGRES_DB: "citizen_portal"
  JWT_SECRET: "<JWT_SECRET_PLACEHOLDER>"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "<ADMIN_PASSWORD_PLACEHOLDER>"
  BACKUP_ENCRYPTION_PASSWORD: "<BACKUP_ENCRYPTION_PASSWORD_PLACEHOLDER>"
