apiVersion: v1
kind: Secret
metadata:
  name: citizen-portal-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  ADMIN_EMAIL: {{ .Values.secret.adminEmail }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword }}
  DATABASE_URL: postgres://{{ .Values.db.user }}:{{ .Values.secret.postgresPassword }}@db-0.db.{{ .Values.namespace }}.svc.cluster.local:5432/{{ .Values.db.name }}
