---
- name: Install Monitoring Stack (Prometheus & Grafana)
  hosts: master
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Create monitoring namespace
      command: k3s kubectl create namespace monitoring
      ignore_errors: yes

    - name: Install Kube-Prometheus-Stack
      command: >
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
        --namespace monitoring --create-namespace
